BlogFest.Web/ViewModels/Content/EditPostViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using BlogFest.Domain.Content;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace BlogFest.Web.ViewModels.Thread
{
    public class EditPostViewModel
    {
        [Required]
        public Guid Id { get; set;}
        public string Title { get; set;}
        public string ContentText{ get; set;}
        public string ContentHTML { get; set;}
        public Guid UserId { get; set; }
        public List<SelectListItem>? Categories { get; set; }
        public List<Guid>? UpdateCategories { get; set; }
        public string? Status { get; set; }
        public string? ImagePath { get; set; }
        public Guid? ImageId { get; set; }
    }
}

BlogFest.Web/Controllers/PostController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BlogFest.Domain.Base;
using BlogFest.Models.Thread;
using BlogFest.Web.Extensions;
using BlogFest.Web.ViewModels.Content;
using BlogFest.Web.ViewModels.Thread;
using BlogFest.Application.Services.Content.Queries.DTOs;
using BlogFest.Application.Services.Content.Queries.GetThreadInfoQuery;
using BlogFest.Application.Services.Content.Queries.GetPostCommentsQuery;
using BlogFest.Application.Services.Content.Queries.GetPostReactionQuery;
using BlogFest.Application.Services.Content.Commands.PutDislike;
using BlogFest.Application.Services.Content.Commands.IncreaseLike;
using BlogFest.Application.Services.Content.Queries.GetPostInfoForEdit;
using BlogFest.Application.Services.Content.Commands.CreateDraftPost;
using BlogFest.Application.Services.Content.Queries.GetAllUserThreadsQuery;
using BlogFest.Application.Services.Content.Commands.PublishPost;
using BlogFest.Web.Filters;
using BlogFest.Application.Services.Content.Commands.EditPost;
using BlogFest.Application.Services.Content.Commands.CreateComment;
using BlogFest.Application.Services.Content.Commands.UploadTitleImage;
using BlogFest.Application.Abstract;
using BlogFest.Application.Services.Content.Queries.GetPostByTitle;
using BlogFest.Application.Services.Media.Results;

namespace BlogFest.Controllers
{
    [Route("post")]
    public class PostController : Controller
    {
        private readonly IUserContext _userContext;
        private readonly ILogger _logger;
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public PostController
            (
            IUserContext userContext, 
            IMediator mediator,
            IMapper mapper
			)
        {
            _userContext = userContext;
            _mediator = mediator;
            _mapper = mapper;
		}

        [HttpGet]
        [Route( "{slug}")]
        public async Task<ActionResult> GetBySlug(string slug)
        {
            var model = await _mediator.Send<PostPageDTO>(new GetPostByTitleQuery
            {
                Slug = slug
            });

            return View("Index", model);
        }

        [HttpGet]
        [Route("{id:guid}")]
        public async Task<ActionResult> Index(Guid Id)
        {
            var model = await _mediator.Send<PostPageDTO>(new GetPostQuery
            {
                PostId = Id
            });

            if(model == null)
            {
                Response.StatusCode = StatusCodes.Status404NotFound;
                return View("NotFound");
            }

            return View(model);
        }

        [HttpGet]
        [Route("comment")]
		public async Task<IActionResult> GetPostComments(Guid postId, int Offset)
        {
            var result = await _mediator.Send<PostCommentsDTO>(new GetPostCommentsQuery
            {
                PostId = postId,
                Offset = Offset
			});

            return PartialView("_GetPostComments", result);
        }

		[HttpPut]
		[Route("post-dislike")]
		[Authorize]
		public async Task<IActionResult> PutDislike(Guid PostId)
		{
			var result = await _mediator.Send<Result<bool, Error>>(new PutDislikeCommand
			{
				PostId = PostId
			});

			var reactions = await _mediator.Send<ReactionDTO>(new GetPostReactionQuery
			{
				PostId = PostId
			});

			var reactionVm = new ReactionViewModel
			{
				LikesCount = reactions.LikesCount,
				DislikesCount = reactions.DislikesCount,
				Type = reactions.Type,
			};

			var htmlResult = await this.RenderViewAsync<ReactionViewModel>("_ReactionButton", reactionVm, true);

			return Json(new { result = true, htmlResult = htmlResult });
		}

		[HttpPut]
        [Route("post-like")]
        [Authorize]
        public async Task<IActionResult> IncreaseLike(Guid PostId)
        {
            var result = await _mediator.Send<Result<bool, Error>>(new IncreaseLikeCommand
            {
                PostId = PostId
            });

			var reactions = await _mediator.Send<ReactionDTO>(new GetPostReactionQuery
			{
				PostId = PostId
			});

			var reactionVm = new ReactionViewModel
            {
                LikesCount = reactions.LikesCount,
                DislikesCount = reactions.DislikesCount,
                Type = reactions.Type,
			};

      		var htmlResult = await this.RenderViewAsync<ReactionViewModel>("_ReactionButton", reactionVm, true);

            return Json(new { result = true, htmlResult = htmlResult });
        }

		[HttpGet]
        [Route("edit")]
        [Authorize]
        public async Task<IActionResult> EditPost(string slug)
        {

            var result = await _mediator.Send<PostEditDTO>(new GetPostInfoForEditQuery
            {
                Slug = slug
            });

            var model = _mapper.Map<EditPostViewModel>(result);
            return View(model);
        }

        [HttpGet]
        [Route("create")]
        [Authorize]
        public async Task<IActionResult> CreatePost()
        {
 
            var result = await _mediator.Send(new CreateDraftPostCommand
            {

                UserId = _userContext.CurrentUserId,

            });

            return result.Match<IActionResult>(x =>
            {
                //model.PostId = result.Value;
                return RedirectToAction("EditPost", new {slug = result.Value.Slug});
            }, x =>
            {
                Response.StatusCode = 400;
         
                return Json(new { error = x });
            } );
        }

        [HttpGet]
        [Route("explore")]
        public async Task <ActionResult> Explore(int page = 1)
        {

            var posts = await  _mediator.Send<ExplorePostsDTO>(new GetAllUserPostsQuery
            {
                Offset = page
            });

            posts.PageIndex = page;

            return View(posts);
        }

        [Route("publish")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        [DefaultValidateModel]
        public async Task<IActionResult> PublishPost(Guid postId)
        {
            var result = await _mediator.Send(new PublishPostCommand
            {
                PostId = postId
            });

            return result.Match<IActionResult>(x => Json(new { result = true, message = "Post has been published" }), x => Json(new {result = false, message = x.Description}));
        }

        [Route("edit")]
        [HttpPut]
        [ValidateAntiForgeryToken]
        [Authorize]
        [DefaultValidateModel]
        public async Task<IActionResult> EditPost(EditPostViewModel model)
        {
            var result = await _mediator.Send(new EditPostCommand
            {
                Title = model.Title,
                ContentText = model.ContentText,
                ContentHTML = model.ContentHTML,
                Categories = model.UpdateCategories,
                PostId = model.Id,
                ImageId = model.ImageId,
                Status =  model.Status 
            });

            return result.Match<IActionResult>(x =>  Json(new  { result = true, message = "Post has been edited" }), x =>  Json(new { result = false, message = x}));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [DefaultValidateModel]
        [Route("comment")]
        [Authorize]
        public async Task<IActionResult> CreateComment(CreateCommentViewModel model)
        {
            var result = await _mediator.Send(new CreateCommentCommand
            {
                UserId = _userContext.CurrentUserId,
                CommentContent = model.CommentContent,
                PostId = model.PostId,
            });

            return result.Match<IActionResult>(x => Json(new { result = true, message = x.Message }), x => Json(new {result = false, error = x.Description } ));
        }

        [HttpPost]
        [Authorize]
        [Route("upload-title-image")]
        [DefaultValidateModel]
        public async Task<IActionResult> UploadTitleImage(UploadImageTitleViewModel model)
        {
            var result = await _mediator.Send<Result<SuccesUploadResult, Error>>(new UploadTitleImageCommand
            {
                Image = await model.GetImageTitleBytesAsync(),
                PostId = model.PostId,
            });

            return result.Match<IActionResult>(x => Json(new { result = true, imageId = x.ImageId ,imageUrl = "/media/" + x.ImagePath  }), x => Json(new { result = false, error = x }));
        } 
    }
}

BlogFest.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using BlogFest.Application;
using MediatR;
using BlogFest.Application.Services.Content.Queries.GetPostByTitle;
using BlogFest.Application.Services.Content.Queries.GetPostsByCategory;
using BlogFest.Application.Services.Search.Queries.DTOs;
using BlogFest.Application.Services.Search.Queries.SearchContent;

namespace BlogFest.Web.Controllers
{
    [Route("/search")]
    public class SearchController : Controller
    {
        private readonly IMediator _mediator;
        public SearchController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet] 
        public async Task<IActionResult> Index(string key, int page = 1)
        {
            var result = await _mediator.Send(new SearchContentQuery
            {
                Key = key,
                Page = page
            });

            return View(result);
        }

        [HttpGet]
        [Route("category")]
        public async Task<IActionResult> Category(string key, int page = 1)
        {
            var posts = await _mediator.Send(new GetPostsByCategoryQuery
            {
                CategoryTitle = key,
                Page = page
            });

            var result = posts.Select(x => new SearchItemDTO
            {
                Id = x.Id,
                Title = x.Title,
                SearchItemType = SearchItemType.Post,
                ImagePath = x.ImagePath,
                Slug = x.Slug,
                UserName = x.UserName,
                Content = x.Text
            }).ToList();

            return View("Index", new SearchDTO
            {
                SearchResult = result
            });
        }
    }
}

BlogFest.Web/Controllers/UserController.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BlogFest.Application.Users.Queries.GetUserInfo;
using BlogFest.Domain.Users;
using BlogFest.Infrastructure.Persistance;
using BlogFest.Models.User;
using System.Net;
using BlogFest.Application.Services.Users.DTOs;
using BlogFest.Application.Abstract;
using BlogFest.Application.Services.Users.Queries.GetUserPageByName;
using BlogFest.Application.Services.Users.Queries.GetAllNotification;
using BlogFest.Application.Services.Users.ReadAllNotifications;

namespace BlogFest.Controllers
{
    [Route("/user")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IUserRepository _userRepository;
        private readonly IMediator _mediator;
        private readonly IUserContext _userContext;
        public UserController(ApplicationDbContext context, IUserRepository userRepository, IMediator mediator, IUserContext userContext)
        {
            _context = context;
            _userRepository = userRepository;
            _mediator = mediator;
            _userContext = userContext;
        }

        [Route("/user/{name}")]
        public async Task<ActionResult> IndexByName(string name, int page = 1)
        {
            var post = await _mediator.Send<UserPageDTO>(new GetUserPageByNameQuery
            {
                Name = name,
                CurrentUserId = _userContext.CurrentUserId,
                Page = page
            });

            if (post == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return View("UserNotFound");
            }

            if (!post.User.IsActive) return View("UserDeactivated");

            return View("Index", post);
        }

        [Route("{id:guid}")]
        public async Task<ActionResult> Index(Guid Id, int page = 1)
        {
            UserViewModel model;

            var post = await _mediator.Send<UserPageDTO>(new GetUserPageQuery
            {
                Id = Id,
                CurrentUserId = _userContext.CurrentUserId,
                Page = page
            });

            if (post == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return View("UserNotFound");
            }

            if (!post.User.IsActive) return View("UserDeactivated");

            return View(post);
        }

        [Route("notification")]
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Notification()
        {
            await _mediator.Send(new ReadAllNotificationsCommand());
            var result = await _mediator.Send<List<NotificationDTO>>(new GetAllUserNotificationQuery());
            return View(result);
        }

        [Route("main")]
        [Authorize]
        public async Task<ActionResult> MainUserPage(int page = 1)
        {
            UserViewModel model;

            if(!_userContext.IsAuthenticated) return Unauthorized();

            var user = await _mediator.Send<UserPageDTO>(new GetUserPageQuery
            {
                Id = _userContext.CurrentUserId,
                CurrentUserId = _userContext.CurrentUserId,
                Page = page

            });

            if (user == null)
            {
                //Response.StatusCode = (int)HttpStatusCode.NotFound;
                //foreach (var cookie in Request.Cookies.Keys)
                //{
                //    Response.Cookies.Delete(cookie);
                //}
                return View("UserNotFound");
            }

            return View("Index", user);
        }
        
    }
}

BlogFest.Web/Views/Post/EditPost.cshtml
@using BlogFest.Domain.Content;
@using BlogFest.Web.ViewModels.Thread;
@using System.Web;
@{
 
    ViewData["Title"] = "Edit Post";
}

@section Styles{
    <link href="~/lib/select2/css/select2.min.css" type="text/css" rel="stylesheet"/>

}

@model EditPostViewModel;


<style>
    #file-preview{
/*        width:100px*/
    }
</style>


<div class="container text-center mb-4">
    @if (!string.IsNullOrEmpty(Model.ImagePath))
    {
        <div class="text-center">
            <img id="preview-image" src="\media\@Model.ImagePath" class="img-fluid">
        </div>
    } else
    {
        <div class="text-center">
            <img id="preview-image"  class="img-fluid">
        </div>
    }

</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <form asp-action="EdithPost" id="EditPostForm" class="form-edit-post" method="post">
                        <input hidden asp-for="Id" />

                        <div class="form-group">
                            <label>Preview Image:</label>
                            <input type="file" id="file-preview" name="ImageTitle" class="form-control" /> <br />
                            <div>
                                <span class="text-danger field-validation-valid"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Title:</label>
                            <input asp-for="Title" class="form-control" /> <br />
                            <div>
                                <span class="text-danger field-validation-valid" asp-validation-for="Title"></span>
                            </div>
                        </div>

                        <div class="form-group">

                            <label>Text:</label>
                            <div id="editor">
                                @Html.Raw(@Model.ContentHTML)

                            </div>
                        </div>

                        <div class="form-group mt-4">
                            <select class="form-select" multiple aria-label=" select example" id="UpdateCategories" name="UpdateCategories" asp-items="Model.Categories">
                            </select>
                        </div>

                        <div class="form-group mt-4">
                            Status:
                            <br />
                            @if (Model.Status != PostStatus.Draft)
                            {
                       
                                @PostStatus.Hidden
                                <input name="Status" type="radio" value="@PostStatus.Hidden"  @{if (Model.Status == PostStatus.Hidden) { <text>checked</text> } } />
                               

                     
                                @PostStatus.Published
                                <input name="Status" type="radio" value="@PostStatus.Published" @{if (Model.Status == PostStatus.Published) { <text>checked</text> } }  />
                             
                            }
                        </div>

                        <div class="form-group mt-4 text-end">
                            <button type="submit" class="btn btn-primary js-save-form">Save</button>

                            @if (Model.Status == PostStatus.Draft)
                            {
                                <button type="submit" class="btn btn-success js-publish-form">Publish Thread</button>
                            }

                        </div>

              

                    </form>
                </div>
            </div>
                
        </div>
    </div>
</div>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script>
        var imageId = '';
        var quill = new Quill('#editor', {
            theme: 'snow'
        });

        var form = $('#EditPostForm')[0];

        $('.js-save-form').on('click', function(e){

            e.preventDefault();

            var data = new FormData(form);
            var editor = document.querySelector('.ql-editor');

            console.log(imageId);

            data.append('ImageId', imageId);
            data.append('ContentHTML', editor.innerHTML);
            data.append('ContentText', editor.innerText);
            data.delete('ImageTitle');

            $.ajax({
                url:"@Url.Action("EditPost")",
                method:"put",
                data: data,
                processData: false,
                contentType:false,
                success: function(data){
                    
                    if(data.result){
                         openSuccessModal(data.message);
                         return;
                    }

                    openDangerModal(data.message.description);
                    
                },
                error:function(data){
                    if(data.status == 400 ) {
                        openDangerModal(data.responseJSON.htmlError);
                        return;
                    }

                    openDefaultDangerModal();
                }
            });
        });

        $('#file-preview').on('change', function(){
           debugger;
           var file = $(this)[0].files[0];
            $('#file-preview').val(null);

           var data = new FormData();

           data.append('ImageTitle', file);
           data.append('PostId', $('#Id').val());
            //data.append('__RequestVerificationToken', document.getElementsByName('__RequestVerificationToken')[0].value);

           $.ajax({
                method:'post',
                url: '@Url.Action("UploadTitleImage")',
                data: data,
                contentType: false,
                processData: false,
       
                success: function(data){
                    console.log(data);
                   if(data.result == false){
                       openDangerModal(data.error.description);
                       return;
                   }

                    $('#preview-image').attr('src', data.imageUrl);
                    imageId = data.imageId;
                },

                error:function(data){
                    console.log(data);
                    openDangerModal("Something went wrong");
                }
           });
        });


        $('.js-publish-form').on('click', function (e) {

            e.preventDefault();


            if ($('.form-edit-post').validate()) {
                $.ajax({
                    url: '@Url.Action("PublishPost")',
                    data: {
                        postId: $('#Id').val(),
                        '__RequestVerificationToken': document.getElementsByName('__RequestVerificationToken')[0].value
                    },
                    method: 'POST',
                    success: function (data) {
                        if (data.result) {
                            alert(data.message);
                            window.location.href = "@Url.Action("MainUserPage", "User")";
                            return;
                        }

                        openDangerModal(data.message);
                    },
                    error: function (data) {

                    }
                });
            }

        });

        $('#UpdateCategories').select2({
            tags: true
        });
    </script>
}

                        

BlogFest.Web/Views/Post/Explore.cshtml
@using System.Web;
@using BlogFest.Application.Services.Administration.Queries.DTOs;
@using BlogFest.Application.Services.Content.Queries.DTOs;
@model ExplorePostsDTO
@{
    Layout = "_ContentLayout";
    var pages = (int)Math.Ceiling((decimal)Model.Count / (decimal)3.0);
}


@if (Model.Posts != null)
{
    for (int i = 0; i < Model.Posts.Count; i++)
    {

        <div class="card mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-4">
                        <img src="\media\@Model.Posts[i].ImagePath" class="img-fluid" />
                    </div>
                    <div class="col-sm-8">
                        <div class="d-flex justify-content-between">

                            <a href="@Url.Action("GetBySlug", "Post", new {Slug = Model.Posts[i].Slug })">
                                <h3 class="title">
                                    @Model.Posts[i].Title

                                </h3>
                            </a>

                        </div>
                        <p class="text-muted"><span class="glyphicon glyphicon-calendar"></span> @Model.Posts[i].DateCreated.ToString("dddd, dd MMMM yyyy")</p>
                        <p>@Model.Posts[i].Text</p>

                        <p class="text-muted">Presented by
                            <a href="@Url.Action("IndexByName", "User", new {name = @Model.Posts[i].UserName})">
                                @Model.Posts[i].UserName
                            </a>
                        </p>

                    </div>
                </div>
            </div>
        </div>
    }
}

@if (Model.Count != 0 && pages > 1)
{
    <nav aria-label="...">
        <ul class="pagination">

            @for (var i = 1; i <= pages; i++)
            {
                @if (i == Model.PageIndex)
                {

                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">@i</a>
                    </li>
                }
                else
                {
                    <li class="page-item" aria-current="page">
                        <a class="page-link" href="@Url.Action("Explore", new {page = i})">@i</a>
                    </li>
                }
            }
        </ul>
    </nav>
}

BlogFest.Web/Views/Post/Index.cshtml
@using BlogFest.Application.Services.Content.Queries.DTOs;
@using System.Web;
@model PostPageDTO
@{
	Layout = "_ContentLayout";
}

@section Styles{
	<style>
		.reply-block {
			display: none;
		}

		.img-sm {
			width: 46px;
			height: 46px;
		}

		.media-block .media-left {
			display: block;
			float: left
		}

		.media-block .media-right {
			float: right
		}

		.media-block .media-body {
			display: block;
			overflow: hidden;
			width: auto
		}

		.middle .media-left,
		.middle .media-right,
		.middle .media-body {
			vertical-align: middle
		}

		.thumbnail {
			border-radius: 0;
			border-color: #e9e9e9
		}

		.tag.tag-sm, .btn-group-sm > .tag {
			padding: 5px 10px;
		}

		.tag:not(.label) {
			background-color: #fff;
			padding: 6px 12px;
			border-radius: 2px;
			border: 1px solid #cdd6e1;
			font-size: 12px;
			line-height: 1.42857;
			vertical-align: middle;
			-webkit-transition: all .15s;
			transition: all .15s;
		}

		.text-muted, a.text-muted:hover, a.text-muted:focus {
			color: #acacac;
		}

		.text-sm {
			font-size: 0.9em;
		}

		.text-5x, .text-4x, .text-5x, .text-2x, .text-lg, .text-sm, .text-xs {
			line-height: 1.25;
		}

		.btn-trans {
			background-color: transparent;
			border-color: transparent;
			color: #929292;
		}

		.btn-icon {
			padding-left: 9px;
			padding-right: 9px;
		}

			.btn-sm, .btn-group-sm > .btn, .btn-icon.btn-sm {
				padding: 5px 10px !important;
			}

		.mar-top {
			margin-top: 15px;
		}

		.content-container {
			max-width: 780px;
			margin: 0 auto;
		}
	</style>
}



<input id="PostId" name="PostId" type="hidden" value="@Model.Id" />

<div class="content-container">

	@if (!string.IsNullOrEmpty(Model.ImagePath))
	{
		<div class="text-center mb-4">
			<img src="\media\@Model.ImagePath" class="img-fluid">
		</div>
	}

	<div class="card">
		<div class="card-body">
			<div>
			</div>
			<div class="d-flex justify-content-between">
				<h3>
					@Model.Title
				</h3>

				<div class="file-loader">
				</div>
			</div>


			<div>
			
				@if (Model.Categories != null && Model.Categories.Count != 0)
				{
					@:Categories:
					foreach (var item in Model.Categories)
					{
						<a href="@Url.Action("Category", "Search", new{key = HttpUtility.UrlEncode(@item.Title)})"><span class="badge bg-secondary">@item.Title</span></a>
					}
				}
			</div>

			<div>
				@Html.Raw(Model.Content)
			</div>
			<div>
				created by <a href=@Url.Action("IndexByName", "User", new {name = "admin"})>
					@Model.CreatedByName
				</a>
			</div>

			<div class="text-end">
				<div class="reaction-wrapper">
					@await Component.InvokeAsync("PostReaction", new{id = Model.Id} )
				
				</div>
			</div>
		</div>
	</div>

	<section class="gradient-custom">
		<div class="container my-5 py-5">
			<div class="row d-flex justify-content-center mb-4">
				<input name="PostId" type="hidden" value="@Model.Id" />

				<div class="card">
					<div class="card-body">
						<form asp-action="CreateComment" id="CreateComment">
							<input name="PostId" type="hidden" value="@Model.Id" />
							<textarea class="form-control" rows="2" name="CommentContent" placeholder="What are you thinking?"></textarea>
							<div class="mar-top clearfix">
								<button class="btn btn-sm btn-primary pull-right comment-reply-js" type="submit"><i class="fa fa-pencil fa-fw"></i> Comment</button>
							</div>
						</form>
					</div>
				</div>

			</div>

			<div class="row d-flex justify-content-center">
				<div class="card">
					<div class="card-body p-4">
						<div class="row">
							<div class="col">
								<div class="comments-wrapper">
									<div class="comments">
										<input asp-for="Offset" type="hidden" />

										@if (Model.Comments != null)
										{
											@foreach (var item in Model.Comments)
											{

												<div class="card mb-4">
													<div class="card-body">
														<div class="d-flex flex-start mb-3">

															<img class="rounded-circle shadow-1-strong me-3"
																 src="\media\@item.Path" alt="avatar" width="65"
																 height="65" />
															<div class="flex-grow-1 flex-shrink-1">
																<div>
																	<div class="d-flex justify-content-between align-items-center">
																		<p class="mb-1">
																			<a href="@Url.Action("IndexByName","User", new {name = item.UserName})">@item.UserName</a>  <span class="small">- @item.DateCreated.ToString("dddd, dd MMMM yyyy")</span>
																		</p>
																	</div>
																	<p class="small mb-0">
																		@item.Content
																	</p>
																</div>
															</div>
														</div>
													</div>
												</div>
											}
										}
									</div>
									@if (Math.Ceiling((float)Model.CommentsCommonAmount / Model.Offset) > 1)
									{
										<div class="text-center">
											<a href="post-load" class="load-comments-js">
												Load more
											</a>
										</div>
									}

						
								</div>
								
							</div>

						</div>
					</div>

				</div>
			</div>
		</div>
	</section>

</div>
@section Scripts{
	<script>

		$(document).on('click', '.btn-dislike-post-js', function (e) {
			e.preventDefault();

			$.ajax({
				method: 'put',
				url: "@Url.Action("PutDislike")",
				data: {
					PostId: $('#PostId').val()
				},
				success: function (data) {
					debugger;
					if (data.result && data.htmlResult != undefined) {
						$('.reaction-wrapper').html(data.htmlResult);
					}
				}
			});
		});

		$(document).on('click', '.btn-like-post-js', function (e) {
			e.preventDefault();

			$.ajax({
				method: 'put',
				url: "@Url.Action("IncreaseLike")",
				data: {
					PostId: $('#PostId').val()
				},
				success: function (data) {
					if (data.result && data.htmlResult != undefined) {
						$('.reaction-wrapper').html(data.htmlResult);
					}
				}
			});
		});

		$(document).on('click', '.load-comments-js', function (e) {
			e.preventDefault();
			debugger;
			$.ajax({
				url: '@Url.Action("GetPostComments", new {postId = Model.Id})',
				method: 'get',
				data:{
					offset: $('#Offset').val()
				},
				success: function(data){
					$('.comments-wrapper').html(data);
				}
			});
		});


		$('#CreateComment').on('submit', function (e) {
			e.preventDefault();
			$.ajax({
				url: "@Url.Action("CreateComment")",
				data: $(this).serialize(),
				method: "post",
				success: function (data) {
					if (data.result) {
						alert("Comment has been created");
						window.location.href = "@Url.Action("GetBySlug", new {slug = Model.Slug})";
						return;
					}
					openDangerModal(data.error);
				},
				errors: function (data) {
					openDefaultDangerModal();
				}
			});
		});
	</script>
}